// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxFUAqvcEzQNovauSwd8Eabtc1m3tUljo',
    appId: '1:303276218464:web:a483f2c98dee8a10e9cb05',
    messagingSenderId: '303276218464',
    projectId: 'seproject-group10-f7a99',
    authDomain: 'seproject-group10-f7a99.firebaseapp.com',
    storageBucket: 'seproject-group10-f7a99.appspot.com',
    measurementId: 'G-KRWRVP2ZG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkvngFHGo9l6STh12TDeTg7UUjUVEE38o',
    appId: '1:303276218464:android:6b5b293e0e4dc61fe9cb05',
    messagingSenderId: '303276218464',
    projectId: 'seproject-group10-f7a99',
    storageBucket: 'seproject-group10-f7a99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9gZmac2k5iSgZrgJxNOBWQcgh6IyRhdU',
    appId: '1:303276218464:ios:0f76a0a3c3b96d10e9cb05',
    messagingSenderId: '303276218464',
    projectId: 'seproject-group10-f7a99',
    storageBucket: 'seproject-group10-f7a99.appspot.com',
    iosClientId: '303276218464-rro23hv7tvmosjpmn4dlrvp02cm7ouib.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantryOrganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9gZmac2k5iSgZrgJxNOBWQcgh6IyRhdU',
    appId: '1:303276218464:ios:0f76a0a3c3b96d10e9cb05',
    messagingSenderId: '303276218464',
    projectId: 'seproject-group10-f7a99',
    storageBucket: 'seproject-group10-f7a99.appspot.com',
    iosClientId: '303276218464-rro23hv7tvmosjpmn4dlrvp02cm7ouib.apps.googleusercontent.com',
    iosBundleId: 'com.example.pantryOrganizer',
  );
}
